CREATE TABLE IF NOT EXISTS Logs (
    LogId INT AUTO_INCREMENT PRIMARY KEY,
    LogDateTime DATETIME(3) NOT NULL,
    LogSeverity VARCHAR(255) NOT NULL,
    LogLibrary VARCHAR(255) NOT NULL,
    LogThread VARCHAR(255) NOT NULL,
    LogDetails TEXT NOT NULL
)